#!/bin/bash
#
# Usage: git2zip [REPODIR]
#
# Creates a zip file of the .git directory of a git repository.
#
# The REPODIR directory must contain a .git subdirectory, which is the
# thing that is zipped up. If no REPODIR is give, uses the current dir.
# Creates a zip file in the current directory with the name REPODIR.zip.
#
# Copyright (c) 2020 Ramses van Zon
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

repodir="${1:-.}"
gitdir="${repodir}/.git"
if ! [ -d "${gitdir}" ]; then
    echo "Error: No git repository found in '${gitdir}'" 1>&2
    exit 1
fi

zipname="${PWD}"/$(basename $(dirname $(readlink -f "${gitdir}"))).zip
gitparent=$(dirname "${gitdir}")
gitname=$(basename "${gitdir}")

cd "${gitparent}"
rm -f "${zipname}" && zip -qr "${zipname}" "${gitname}" && echo "${zipname}" created.

